services:
  api:
    build: "."
    ports:
      - "8000:5000"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_URL: ${DB_URL}
      DB_PORT: ${DB_PORT}
    volumes:
      - ./config/config.yaml:/app/config.yaml
      - /app/tmp
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
        - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

#volumes:
#  postgres_data: